services:
  viewer:
    build: ./f1tenth_view
    volumes:
      - ./f1tenth_view:/f1tenth_view
      - /dev/input:/dev/input:ro
      - /dev/dri:/dev/dri
      # Bind the X11 socket from the host
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/pipewire-0:/tmp/pipewire-0
    environment:
      # Tell apps inside the container where to find the X11 display
      - XDG_RUNTIME_DIR=/tmp
      - DISPLAY=${DISPLAY}
      # GPU support
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute,display
      # If using AMD/Intel, these are used by Mesa.
      # The oibaf PPA in the Dockerfile provides latest drivers.
      #- LIBGL_ALWAYS_SOFTWARE=1
      # ROS Discovery
      - CAR_ADDR=${CAR_ADDR}
      - ROS_DISCOVERY_SERVER=${CAR_ADDR}:11811
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    ipc: host
